# Generated by Django 2.0.7 on 2018-09-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionBase',
            new_name='Inscription',
        ),
    ]
