# Generated by Django 2.0.7 on 2018-09-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('sujet', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=200)),
                ('envoyeur', models.EmailField(max_length=45)),
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
