# Generated by Django 2.0.7 on 2018-09-24 17:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_msg',
            field=models.DateField(default=datetime.datetime(2018, 9, 24, 17, 57, 4, 411877, tzinfo=utc)),
        ),
    ]
