# Generated by Django 2.0.7 on 2018-09-25 12:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20180924_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_msg',
            field=models.DateField(default=datetime.datetime(2018, 9, 25, 12, 2, 41, 20420, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='heure_msg',
            field=models.TimeField(default=datetime.datetime(2018, 9, 25, 12, 2, 41, 20420, tzinfo=utc)),
        ),
    ]
